// <auto-generated />
namespace PrantiksmeApp.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedData_For_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedData_For_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201905050544558_SeedData_For_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
